config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  get 'game/:id' => 'games#show', as: :game
  post 'games' => 'games#create', as: :games

  post 'game/:id/hit' => 'games#hit', as: :hit_game
  patch 'game/:id/stay' => 'games#stay', as: :stay_game

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :game
  belongs_to :hand
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :hands
  has_many :cards

  def build_cards
    # 52 cards
    # 2 -> 10
    # J, Q, K (value 10)
    # A (value 11)
    # all have suits "H", "D", "C", "S"

    suits = ["H", "D", "C", "S"]
    positions = (1..52).to_a.shuffle

    suits.each do |suit|
      (2..10).each do |val|
        cards.create suit: suit, value: val, name: val, position: positions.shift
      end
      ["J", "Q", "K"].each do |val|
        cards.create suit: suit, value: 10, name: val, position: positions.shift
      end
      cards.create suit: suit, value: 11, name: "A", position: positions.shift
    end
  end

  player_count = 0

  def deck
    cards.where(hand_id: nil).order("position")
  end

  def player_hand
    hands.find_by player: true
  end

  def dealer_hand
    hands.find_by player: false
  end
end

app/models/hand.rb
class Hand < ActiveRecord::Base
  belongs_to :game
  has_many :cards

  def total
    cards.pluck(:value).sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  outcome = nil

  def index
  end

  def show
    @game = Game.find params[:id]

    if ((@game.dealer_hand.cards.count == 2) && (@game.dealer_hand.total == 21)) && ((@game.player_hand.cards.count == 2) && (@game.player_hand.total == 21))
      @game.dealer_hand.blackjack = true
      @game.player_hand.blackjack = true
      @game.push = true
      @game.dealer_hand.dealer_must_reveal = true
    elsif (@game.player_hand.cards.count == 2) && (@game.player_hand.total == 21)
      @game.player_hand.blackjack = true
      @game.player_wins = true
    elsif (@game.dealer_hand.cards.count == 2) && (@game.dealer_hand.total == 21)
      @game.dealer_hand.blackjack = true
      @game.dealer_wins = true
      @game.dealer_hand.dealer_must_reveal = true
    elsif (@game.player_hand.total > 21)
      @game.dealer_wins = true
    elsif (@game.player_hand.cards.count == 6)
      @game.player_wins = true
    elsif (@game.dealer_hand.total >= 17) && (@game.player_stayed == true)
      if @game.dealer_hand.total > 21
        @game.player_wins = true
        @game.dealer_hand.dealer_must_reveal = true
      elsif @game.dealer_hand.total > @game.player_hand.total
        @game.dealer_wins = true
        @game.dealer_hand.dealer_must_reveal = true
      elsif @game.dealer_hand.total == @game.player_hand.total
        @game.push = true
        @game.dealer_hand.dealer_must_reveal = true
      elsif @game.player_hand.total > @game.dealer_hand.total
        @game.player_wins = true
        @game.dealer_hand.dealer_must_reveal = true
      end
    end

    @player_wins = @game.player_wins
  end

  def create
    @game = Game.create
    @game.build_cards

    player_hand = Hand.create game_id: @game.id, player: true
    dealer_hand = Hand.create game_id: @game.id, player: false

    player_hand.cards << @game.deck.first
    dealer_hand.cards << @game.deck.second

    player_hand.cards << @game.deck.third
    dealer_hand.cards << @game.deck.fourth

    redirect_to game_path(id: @game.id)
  end

  def hit
    @game = Game.find params[:id]

    if @game.player_hand.total < 21
      @game.player_hand.cards << @game.deck.first
    end
    redirect_to game_path(id: @game.id)
  end

  def stay
    @game = Game.find params[:id]

    @game.player_stayed = true
    @game.save
    if @game.dealer_hand.total < 17
      until @game.dealer_hand.total >= 17
        @game.dealer_hand.cards << @game.deck.first
      end
    end

    redirect_to game_path(id: @game.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/index.html.erb
<%= link_to 'Begin Game', games_path, method: :post, class: 'btn btn-success btn-default' %>

app/views/games/show.html.erb
<div class="playing">
  <% if (@game.player_wins == false) && (@game.dealer_wins == false) && (@game.push == false) %>
    <%= link_to "Hit", hit_game_path(id: @game.id), class: "btn btn-success btn-lg", method: :post %>
    <%= link_to "Stay", stay_game_path(id: @game.id), class: "btn btn-success btn-lg", method: :patch %>
  <% end %>
  <%= link_to "Play Again", games_path, class: "btn btn-success btn-lg", method: :post %>
  <div class="Winner">
    <% if @game.player_wins == true %>
      <% if @game.player_hand.blackjack == true %>
        <h1>Blackjack, MoFo!<h1>
      <% else %>
        <h2>You win! Congratulations!</h2>
      <% end %>
    <% elsif @game.dealer_wins == true %>
        <h2>Sorry...Dealer wins. Please try again.</h2>
    <% elsif @game.push == true %>
        <h2>Push. A tie is not win, but it is not a loss either.</h2>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-6">
    <h3 class="hands">Player Hand</h3>
      <% @game.player_hand.cards.each do |card| %>
          <%= image_tag "#{card.name}#{card.suit}.png" %>
      <% end %>
  </div>
  <div class="col-xs-6">
    <h3 class="hands">Dealer Hand</h3>
    <% if @game.dealer_hand.cards.count == 2 %>
      <%= image_tag "#{@game.dealer_hand.cards.first.name}#{@game.dealer_hand.cards.first.suit}.png" %>
      <% if @game.dealer_hand.dealer_must_reveal == false %>
        <%= image_tag "card-back.png"%>
      <% else %>
        <%= image_tag "#{@game.dealer_hand.cards.second.name}#{@game.dealer_hand.cards.second.suit}.png" %>
      <% end %>
    <% elsif @game.dealer_hand.cards.count > 2 %>
      <% @game.dealer_hand.cards.each do |card| %>
        <%= image_tag "#{card.name}#{card.suit}.png" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blackjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="my_header_box">
    <div class="my_header">
      <h2>My Blackjack</h2>
    </div>
  </div>
  <div class="my_content">
    <%= yield %>
  </div>
</body>
</html>